### ISSUE TITLE
Strange error with facetted map

### ISSUE THREAD

**Issue by Robinlovelace** [mtennekes/tmap#105]
Reproducible example:

```r
data("World")
tm_shape(World) +
    tm_fill("pop_est", thres.poly = 0) +
tm_facets("name", free.coords=TRUE, drop.units=TRUE) +
    tm_layout(legend.show = FALSE, title.position = "centre", title.size = 20)
```

For me this generates:

```
Error in plot_all(1, list(tmLayer1 = list(npol = 177L, varnames = list( : 
  object 'treeMapX' not found
```

Originally reported in my tutorial thanks to @SteveM49.

**Comment by Robinlovelace** [comment]
Original report: https://github.com/Robinlovelace/Creating-maps-in-R/issues/33

**Comment by Robinlovelace** [comment]
Update: also fails on dev version. Seems to be due to the `legend.show` bit - this also fails as the last line in my example:

```
    tm_layout(legend.show = FALSE)
```

**Comment by mtennekes** [comment]
Thanks for reporting this! The bug should be fixed now.

The placement of the title(s) can be a bit confusing, especially for facets. What title(s) do you want to show? One title of the whole plot, or the title per facet? 

A title for each facet is possible as follows:
	
    tm_shape(World) +
        tm_fill("pop_est", thres.poly = 0) +
        tm_facets("name", free.coords=TRUE, drop.units=TRUE) +
        tm_layout(panel.label.size = 2, legend.show = FALSE)

By design, a title for the whole plot is only possible as part of the legend:

    tm_shape(World) +
        tm_fill("pop_est", thres.poly = 0) +
        tm_facets("name", free.coords=TRUE, drop.units=TRUE) +
        tm_layout(legend.show = TRUE, title="My Title", title.size=2)

Note 1: `title.size=20` is HUGE, since the sizes are relative.
Note 2: `title.position` takes a vector of 2, e.g. `c("center", "top")`.

Currently, the legend and the map attributes (as a whole) can be placed outside the map with `legend.outside(.position)` and `attr.outside(.position)`. Furthermore, the title is placed inside the map (even though there are facets), unless the legend is placed outside the map. Maybe it makes sense to add `title.outside` as well. In that case, the only logical position would be above the map, I think.

**Comment by Robinlovelace** [comment]
Many thanks for the fix, great work sir! Regarding the titles, the original had them in the center of each plot. Still possible? No worries if not, neater to have them in the facet heading.
