### ISSUE TITLE
Question: tmaps recognizable as ggplot2 classes?

### ISSUE THREAD

**Issue by mikedolanfliss** [mtennekes/tmap#118]
This is a fantastic package, a huge step forward in map-making in R.

I'm sure it made sense for many reasons to create tmap objects of their own structure rather than trying to extend ggplot2 directly so that the final plot objects are ggplot classes (meaning things like ggplotly() or ggplot layers would work on them, but I'm curious if there might be any plan to integrate those two systems rather than tmap (fantastically!) mimicking ggplot grammar, but being largely separate, if similarly languaged, systems.

**Comment by mtennekes** [comment]
Yeah, could be a nice addition. However, I don't know the ggplot2 internals. Probably, it will be relatively easy to translate a tmap plot call to a ggplot2 one, especially regarding the shape and aesthetics. For other thinks, like legend and map attributes, it may take more effort.

**Comment by microly** [comment]
it will be a great event to integrate tmap with ggplot2, because geom_sf is not so mature and not so good to use. tmap works much better.

it is no so hard to do this.

@mtennekes，please check this：
http://ggplot2.tidyverse.org/articles/extending-ggplot2.html

1.you can create new stats for border, line, and points, which read and transform sf class to x-y  coordinate. 
2.create new ggplot2 layer by combing the new stats with build-in geom such as polygon, line and point. 
3.then you can plot the main part of map.
4.as the scale bar, north arrow, you can create new geom for them, just like the R package 'ggsn'.

step 1 is the most important one, which open up the geometry column of sf and pick out the  x-y  coordinate of geography feature.

I want to try it myself, but the code of tmap is too deep for me. It is hard to find out and understand the code which process  sf.

**Comment by microly** [comment]
just like the example in 
http://ggplot2.tidyverse.org/articles/extending-ggplot2.html

you can create 'StatChull' to process sf in  compute_group function.
then create 'stat_chull' by combine 'StatChull' with [ geom = "polygon"].
at last, you can draw the border of sf through ' ggplot() + 'stat_chull'()'.

**Comment by mtennekes** [comment]
Why? What kind of integration are you looking for?

**Comment by Nowosad** [comment]
For people looking on how to create maps with **ggplot2** try https://paleolimbot.github.io/ggspatial/.
