### ISSUE TITLE
tmap_facets bug ?

### ISSUE THREAD

**Issue by GreenStat** [mtennekes/tmap#136]
whilst experimenting with tmap and  plotting with tmap_facets,  it gives me this unexpected behaviour:
an example :

```{r, echo=FALSE}
# librarys...
library(sf)
library(tmap)
library(tidyverse)
```

```{r, echo=TRUE}
data(Europe)
nl.sf <- Europe %>% st_as_sf() %>% filter(name=="Netherlands")
nl.sf %>% tm_shape() + tm_polygons()
# 
```

data is in long format, the example repeats a polygon 3 times with different attribute values 'scen' and 'y'.

```{r, echo=FALSE}
nl_all.sf <- rbind(
nl.sf %>% mutate(yr=2010, scen=1,y=runif(1,0,10) ),
nl.sf %>% mutate(yr=2010, scen=2,y=runif(1,0,10) ),
nl.sf %>% mutate(yr=2010, scen=3,y=runif(1,0,10) ))
```

plotting this with tmap_facets:
```{r, echo=FALSE}
brks=c(0,2,4,6,8,10)
nl_all.sf %>% tm_shape() + tm_polygons("y", breaks=brks) + tm_facets(c('yr','scen'))
```
gives me : scen 1 and scen 2 are empty
![plot1](https://user-images.githubusercontent.com/25354039/30227379-cdfd2c74-94d9-11e7-90b0-d3641a38aa84.jpg)

alternative method:
```{r, echo=FALSE}
brks=c(0,2,4,6,8,10)
m1<-nl_all.sf %>% filter(yr==2010 & scen==1 ) %>% tm_shape() + tm_polygons("y", breaks=brks,title="scen 1")
m2<-nl_all.sf %>% filter(yr==2010 & scen==2 ) %>% tm_shape() + tm_polygons("y", breaks=brks,title="scen 2")
m3<-nl_all.sf %>% filter(yr==2010 & scen==3 ) %>% tm_shape() + tm_polygons("y", breaks=brks,title="scen 3")

tmap_arrange(m1,m2,m3, nrow=1, asp=1)
```
gives : 

![plot2b](https://user-images.githubusercontent.com/25354039/30227972-0b64924e-94dc-11e7-995c-ee617afdd48a.jpg)

It seems that  '+ tm_facets(c(var1,var2))' is not plotting all the available data...

For this example  the workaround is oke, but when my yr*scen list is much longer I prefer the tm_facets way to work.

Peter

**Comment by mtennekes** [comment]
Ah, this one again:-) It's not a bug, but an effect of using identical polygons. Since missing values are also plotted (by default gray), all three polygons are plotted in each facet. Since the third polygon is drawn op top of the other two, only the third facet is colored (since an y value is missing for scen 1 and 2). Example of what I mean:

    nl_all.sf <- rbind(
      nl.sf %>% mutate(yr=2010, scen=1,y=runif(1,0,10) ),
      nl.sf %>% st_set_geometry(nl.sf$geometry + c(0, 10000)) %>% 
        st_set_crs(st_crs(nl.sf)) %>% mutate(yr=2010, scen=2,y=runif(1,0,10) ),
      nl.sf %>% st_set_geometry(nl.sf$geometry + c(0, 20000)) %>% 
        st_set_crs(st_crs(nl.sf)) %>% mutate(yr=2010, scen=3,y=runif(1,0,10) ))

    nl_all.sf %>% tm_shape() + tm_polygons("y", breaks=brks) + tm_facets(c('yr','scen'))

gives:

![rplot](https://user-images.githubusercontent.com/2444081/30397363-ed7997e4-98cc-11e7-84eb-22ffc3f10532.png)

You can drop the polygons with missing values as follows:

nl_all.sf %>% tm_shape() + tm_polygons("y", breaks=brks) + tm_facets(c('yr','scen'), drop.units = TRUE)

![rplot01](https://user-images.githubusercontent.com/2444081/30397378-ff142f14-98cc-11e7-8d67-e62d6da3dc8c.png)
