### ISSUE TITLE
Facets by two variables

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#14]
I'd love to be able to facet maps by two variables, like in `ggplot2` for instance. And this would be all the more useful that with `ggplot2` you can't have free fill scales for choropleth maps.

**Comment by mtennekes** [comment]
Done! See the branch `panels` and the examples in https://github.com/mtennekes/tmap/blob/panels/examples/tm_facets.R. E.g.:
![rplot03](https://cloud.githubusercontent.com/assets/2444081/13650338/76c27a64-e642-11e5-9e8a-237ebb3d5c08.png)

Also, it is possible to apply the panel-based style to single-variable-facets or single maps. And to draw to legend outside of the map, very useful for small multiples with a common legend. I'll have to check the stability, clean up the code, examples and docs.

I'll leave this thread open, so that feedback, bugs, and requests can be posted. Please let me know if you have any.

**Comment by mtennekes** [comment]
Working and merged with the master branch.
