### ISSUE TITLE
Giving layers names that are colours breaks plots

### ISSUE THREAD

**Issue by barryrowlingson** [mtennekes/tmap#140]
I have a 3-band image raster. The following all works fine:

```
> r = stack("./Data/rwanda-bm.tif")
> plotRGB(r)
> tm_shape(r) + tm_rgb()
> tm_shape(r[[1]]) + tm_raster()
> names(r)
[1] "rwanda.bm.1" "rwanda.bm.2" "rwanda.bm.3"
```

but if I change the names to reflect the nature of each band (this is for teaching purposes) then plotting rails, and I just get a big coloured square - red for the first layer:

```
> names(r)=c("red","green","blue")
> tm_shape(r[[1]]) + tm_raster()
```

green for `r[[2]]` and so on. What I really expected was an image of the intensity of the layer, using the default colour palette. If I change the names to:

```
> names(r)=c("red-layer","green-layer","blue-layer")
```

then it works. But that's a workaround.

Using tmap_1.10 fresh off CRAN.

Barry

**Comment by mtennekes** [comment]
Using color names as variables for aesthetics does not work in tmap, because color names are used as fixed constants. (When tm_raster is called without arguments, the first data variable is taken, in your case, "red")

    data(World)
    qtm(World, fill="red")

    qtm(World, fill="life_exp")
 
    names(World)[13] <- "blue"
    qtm(World, fill="blue")

    names(World)[13] <- "Blue"
    qtm(World, fill="Blue")

Maybe I could build some procedure that first checks whether the aesthetic argument is a data column data name (after it checks whether it is a color).
