### ISSUE TITLE
Hexbin raster map feature?

### ISSUE THREAD

**Issue by mbacou** [mtennekes/tmap#161]
I am looking to create a bivariate **raster** map (similar to http://www.esri.com/products/maps-we-love/five-year-drought) using hexagonal features by varying both size and color. I think this is feasible using `ggplot2` and `hexbin` packages, though I would rather use a tmap approach if at all feasible.
Do I need to create my own hexagonal vector shape and pass it to `tmap_icons()` or is there a more straightforward approach?
Thanks for any tip.

![image](https://user-images.githubusercontent.com/260325/34436433-f77377de-ec63-11e7-993b-e1f12d6f6b9f.png)

**Comment by mtennekes** [comment]
Interesting one. I also fancy these hexagon maps. For normal hexagon maps (with constant size) one approach is to create spatial hexagon-shaped polygons, and treat them as 'normal' polygons, e.g.with tm_polygons. For instance 
https://stackoverflow.com/questions/29374004/how-do-i-generate-a-hexagonal-grid-in-r

For this size varying, you can use the same approach, and afterwards shrink the hexagons according to the size variable. This is not ideal since you'll have to write a function to change the shape prior to plotting it.

Your suggestion to use icons is probably better. You'll still need to calculate the positions of the hexagon tiles. For the icons, it is better to avoid tmap_icons, and use a grob object instead. One is enough, since tm_symbols can handle both color and size.
