### ISSUE TITLE
Multiple Basemaps?

### ISSUE THREAD

**Issue by raetaylorburns** [mtennekes/tmap#179]
Hi there,
I am hoping to use a couple different basemaps in the same map... I am using the code: tm_layout(basemaps = c("Stamen.TonerLines", "Stamen.TonerLabels", "MtbMap"))
but only the first basemap appears... Am I missing something or trying to do this incorrectly? Changing the alpha values doesn't seem to solve the problem.
Thank you,
Rae

**Comment by mtennekes** [comment]
It's possible now! 

I've added two functions `tm_basemap` and `tm_tiles`. You'll probably need to latest github version leaflet to make it work. For the implementation I had to make a workaround, since there is an issue with the order of layers (https://github.com/rstudio/leaflet/issues/427).

The examples in https://github.com/mtennekes/tmap/blob/master/examples/tm_tiles.R should work.
