### ISSUE TITLE
Categorical raster plot

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#204]
Raster object could have categorical values represented by attributes. Is is possible to plot them using **tmap**?:

``` r
library(tmap)
library(spData)
data("grain")

tm_shape(grain) + 
  tm_raster() 
#> Warning: No 'levels' column found in data@attributes.
#> Linking to GEOS 3.6.1, GDAL 2.1.4, proj.4 4.9.3
```

![](https://i.imgur.com/jgUvgI4.png)

Created on 2018-05-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mtennekes** [comment]
Thx @Nowosad !

**Comment by Nowosad** [comment]
How about more complex data:

``` r
library(tmap)
library(spData)
library(raster)
#> Loading required package: sp
data("grain")

levels(grain)[[1]]$VALUE2 = c("a", "b", "c")
grain
#> class       : RasterLayer 
#> dimensions  : 6, 6, 36  (nrow, ncol, ncell)
#> resolution  : 0.5, 0.5  (x, y)
#> extent      : -1.5, 1.5, -1.5, 1.5  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 
#> data source : in memory
#> names       : layer 
#> values      : 1, 3  (min, max)
#> attributes  :
#>  ID VALUE VALUE2
#>   1  clay      a
#>   2  silt      b
#>   3  sand      c

tm_shape(grain) + 
  tm_raster(col = "VALUE") 
#> Linking to GEOS 3.6.1, GDAL 2.1.4, proj.4 4.9.3
```

![](https://i.imgur.com/Rrxump1.png)

``` r

tm_shape(grain) + 
  tm_raster(col = "VALUE2") 
```

![](https://i.imgur.com/RoC8dU5.png)

Created on 2018-05-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mtennekes** [comment]
Nice coincidence, I was just looking at this issue:-)

**Comment by mtennekes** [comment]
Raster objects are quite hard to process. Very simple aspects, like variable names and levels can be hidden quite deeply in the data object.

As far as I know, you'll have to use a RasterBrick when you want to have multiple variables, e.g. the `data(land)` object. For one RasterLayer, I don't know whether there is a variable name. For RasterStacks and Bricks they are an attribute of the values:

```
d> str(land)
Formal class 'RasterBrick' [package "raster"] with 12 slots
  ..@ file    :Formal class '.RasterFile' [package "raster"] with 13 slots
  .. .. ..@ name        : chr ""
  .. .. ..@ datanotation: chr "FLT4S"
  .. .. ..@ byteorder   : chr "little"
  .. .. ..@ nodatavalue : num -Inf
  .. .. ..@ NAchanged   : logi FALSE
  .. .. ..@ nbands      : int 1
  .. .. ..@ bandorder   : chr "BIL"
  .. .. ..@ offset      : int 0
  .. .. ..@ toptobottom : logi TRUE
  .. .. ..@ blockrows   : int 0
  .. .. ..@ blockcols   : int 0
  .. .. ..@ driver      : chr ""
  .. .. ..@ open        : logi FALSE
  ..@ data    :Formal class '.MultipleRasterData' [package "raster"] with 14 slots
  .. .. ..@ values    : int [1:583200, 1:4] 20 20 20 20 20 20 20 20 20 20 ...
  .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. ..$ : NULL
  .. .. .. .. ..$ : chr [1:4] "cover" "cover_cls" "trees" "elevation"
```

The levels can be found in `@data@attributes`, which is apparently also accessible via `levels`. This is a list, with per categorical variable a `data.frame` with the ID numbers and the categories. The names of this data.frame are not really consistent, and it can also have a COUNT column. What I did to make it robust, is to assume the first column contains the integer numbers, and the last column the category labels. So far, this worked with all the raster objects I tried.

**Comment by Nowosad** [comment]
Another example - a simple rasterization. The problem here is the output plot will be the last column in the attributes...

``` r
library(raster)
#> Loading required package: sp
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.4, proj.4 4.9.3
library(spData)

ohio = subset(us_states, NAME == "Ohio")

raster_template = raster(extent(ohio), resolution = 0.5,
                          crs = st_crs(ohio)$proj4string)

ohio_raster = rasterize(as(ohio, "Spatial"), raster_template)
ohio_raster
#> class       : RasterLayer 
#> dimensions  : 7, 9, 63  (nrow, ncol, ncell)
#> resolution  : 0.5, 0.5  (x, y)
#> extent      : -84.82016, -80.32016, 38.47752, 41.97752  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0 
#> data source : in memory
#> names       : layer 
#> values      : 1, 1  (min, max)
#> attributes  :
#>  ID GEOID NAME  REGION          AREA total_pop_10 total_pop_15
#>   1    39 Ohio Midwest 107051.4 km^2     11512431     11575977
```

Created on 2018-06-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mtennekes** [comment]
Ok, `ohio_raster` is a `RasterLayer`, and therefore contains one variable. As I wrote before, the variable name in a `RasterLayer` is unknown, whereas they are stored in a `RasterBrick`: compare `plot(tmap::land)` with `plot(ohio_raster)`.

What are the levels of `ohio_raster`, or what should they be?

```{r}
raster::is.factor(ohio_raster)
#> [1] TRUE

levels(ohio_raster)
#> [[ 1]]
#>    ID GEOID NAME  REGION          AREA total_pop_10 total_pop_15
#> 41  1    39 Ohio Midwest 107051.4 km^2     11512431     11575977
```

??? What does this mean? A factor with multiple sets of levels? However, `total_pop_10` and `total_pop_15` are numeric by origin.



I would expect that `rasterize` returns a `RasterBrick` instead. According to the documentation a `RasterBrick` is only returned when multiple functions are specified. Two years ago, I wrote a wrapper around it to solve this issue (`tmaptools::poly_to_raster`,) which still relies on `sp` methods.

Do you have any suggestion how to tackle these raster objects? For `RasterLayer`s with `is.factor == TRUE`, I could assume that all variables in the levels' data.frame except `ID` and `COUNT` can be considered as (categorical) variables. However, I'm not sure it this is true for all raster objects.

**Comment by mtennekes** [comment]
Ah, this confirms my suggested approach:

```r
library(sp)                                                  
ohio_raster2 <- as(ohio_raster, "SpatialGridDataFrame")      
str(ohio_raster2)                                            
#> Formal class 'SpatialGridDataFrame' [package "sp"] with 4 slots
#>   ..@ data       :'data.frame':  63 obs. of  6 variables:
#>   .. ..$ GEOID       : chr [1:63] NA NA "39" NA ...
#>   .. ..$ NAME        : chr [1:63] NA NA "Ohio" NA ...
#>   .. ..$ REGION      : Factor w/ 4 levels "Norteast","Midwest",..: NA NA 2 NA NA NA NA 2 2 2 ...
#>   .. ..$ AREA        :Class 'units'  atomic [1:63] NA NA 107051 NA NA ...
#>   .. .. .. ..- attr(*, "units")=List of 2
#>   .. .. .. .. ..$ numerator  : chr [1:2] "km" "km"
#>   .. .. .. .. ..$ denominator: chr(0) 
#>   .. .. .. .. ..- attr(*, "class")= chr "symbolic_units"
#>   .. ..$ total_pop_10: num [1:63] NA NA 11512431 NA NA ...
#>   .. ..$ total_pop_15: num [1:63] NA NA 11575977 NA NA ...
#>   ..@ grid       :Formal class 'GridTopology' [package "sp"] with 3 slots
#>   .. .. ..@ cellcentre.offset: Named num [1:2] -84.6 38.7
#>   .. .. .. ..- attr(*, "names")= chr [1:2] "s1" "s2"
#>   .. .. ..@ cellsize         : num [1:2] 0.5 0.5
#>   .. .. ..@ cells.dim        : int [1:2] 9 7
#>   ..@ bbox       : num [1:2, 1:2] -84.8 38.5 -80.3 42
#>   .. ..- attr(*, "dimnames")=List of 2
#>   .. .. ..$ : chr [1:2] "s1" "s2"
#>   .. .. ..$ : chr [1:2] "min" "max"
#>   ..@ proj4string:Formal class 'CRS' [package "sp"] with 1 slot
#>   .. .. ..@ projargs: chr "+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0"
```

**Comment by mtennekes** [comment]
I finally read some docs about it:-)

What is returned by the `levels` function is a so-called RAT table, which can be extracted by `as.data.frame`. However, this function is a lot slower than tmaps internal function `get_raster_data`. Furthermore, for RasterBrick objects, it uses `layername_ratcolumn` notation, while in many cases the layername is sufficient if there is a unique rat column (besides ID).

**Comment by Nowosad** [comment]
Hey @mtennekes - I still haven't found enough time to analyze it properly.. However, is it possible to keep the default raster<->tmap behavior, but also add a new option to specify a plotted variable? This would just work for factor rasters (`is.factor(my_raster) == TRUE`):

```
library(tmap)
library(spData)
data("grain")

tm_shape(grain) + 
  tm_raster(col = "ID") 
```

**Comment by mtennekes** [comment]
I've started a 'raster' branch to renew the raster implementation.

The function `get_raster_data` will get all the raster data into a data.frame. For each layer with numeric data, it adds a numeric column, and for each categorical raster layer, it adds a column for each variable in the RAT table, except for ID and COUNT, since they are special meanings, and are non-unique.  If there are non-unique names across RAT tables (e.g. in a RasterStack with multiple layers), the layer name is added as a prefix.

See https://github.com/mtennekes/tmap/blob/raster/sandbox/raster_data.rmd, which tests different kinds of raster objects. If there are any type of raster objects that you miss, please let me know.

**Comment by Nowosad** [comment]
Two questions:
1. What do you think should be a default action of `tm_raster()` on a categorical raster? Right now is a facet plot (see below), but I think it should be just one panel (because it is a RasterLayer). It could be based on either values (1 to 8 in this case) or the last column (levels) like it was before. I prefer the first one. Additionally, a user can specify it using the `col` argument for non-standard plots (I've tried it and it works great).

``` r
library(spDataLarge)
library(raster)
library(tmap)

data(nlcd)

tm_shape(nlcd) + tm_raster()
```

![](https://i.imgur.com/7MPC9sh.png)

Created on 2018-06-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

2. Why the ID cannot be used in the `col` argument? I think it could be useful...

**Comment by mtennekes** [comment]
Thanks for your input!

I agree on your first point, which is implemented now. So by default, one variable per raster layer is shown. This is the first variable (apart from ID and COUNT). I also added some messages, since it maybe unclear which raster variable can be used.

I disagree with your second point:
* Most importantly, `ID` is similar as the `as.integer()` vector from factor variables, which cannot be selected either (e.g. `tm_shape(World[, "economy"]) + tm_polygons("ID")` will not work)
* Secondly, `ID` is used in every RAT table, so for bricks and stacks with multiple categorical layers, ID variables can only be distinguished with `layer.1.ID`. Of course, for `RasterLayer`, variables don't have to be prefixed with the layer name.
* Third, in many cases, e.g. the `land` data in tmap, raster objects consist of only one variable per RAT table (besides ID and COUNT). It does not make sense to show to ID values of `cover` and `cover_cls` rather than the factor labels when running `qtm(land)`. I could implement a rule like "if a RAT table only has one variable (besides ID and COUNT), use that variable, and otherwise, use the ID variable". However, this will add more complexity which isn't very user friendly. What do you think?

I'm open to suggestions. Did you take a look at https://github.com/mtennekes/tmap/blob/master/sandbox/raster_data.rmd? I tried to collect as many raster format types as possible, and test tmap on them. Let me know if there are cases in which improvements can be made, or if there are cases missing.

**Comment by Nowosad** [comment]
Thanks for the answer. 
Yes, I've seen the raster_data file - I am unable to think about different examples right now. I will let you now in the future if this would change.

**Comment by Si-Chong** [comment]
I am using tmap version 3.0, and the same code as:

```
library(tmap)
library(spData)
data("grain")
tm_shape(grain) + 
  tm_raster()
```

And I get this blank map. Is this because of the version? As I remember when Jakub taught us, it was not like this... Thanks for helping me out!
![Rplot](https://user-images.githubusercontent.com/49397144/85934121-58c46700-b8d6-11ea-9c87-483e933ecd6c.jpeg)

**Comment by Nowosad** [comment]
Hi @Si-Chong - there was a bug in tmap 3.0 - it is now fixed in the development version. You need to install the dev versions of both tmaptools and tmap from github: 

```r
library(remotes)
install_github("mtennekes/tmaptools")
install_github("mtennekes/tmap")
```

**Comment by Si-Chong** [comment]
Thank you, Jakub. All solved.
