### ISSUE TITLE
legend with multiple columns

### ISSUE THREAD

**Issue by jannes-m** [mtennekes/tmap#230]
Hey Martijn, 
this might be a simple question, but I couldn't find a solution. Is it possible to spread the legend across multiple columns, e.g., at the bottom of a figure?
All the best!

**Comment by mtennekes** [comment]
Yep, one of the `tm_symbol` examples:

```
data(metro)
tm_shape(metro) +
	tm_symbols(size = "pop2010", col="pop2010", shape="pop2010",
		legend.format = list(text.align="right", text.to.columns = TRUE)) +
tm_legend(outside = TRUE, outside.position = "bottom", stack = "horizontal")
```

Is this what you meant?

**Comment by jannes-m** [comment]
Thanks for the quick answer, but no, this is not exactly what I meant, though interesting!
Sorry, I should have added an example before:

```r
library("sp")
example("meuse", echo = FALSE)
spplot(meuse, "elev", auto.key = list(columns = 3))
```

**Comment by mtennekes** [comment]
That's not possible, but you have change the orientation of the legend with `legend.is.portrait`. This is as close you can get:

```
tm_shape(meuse)
  tm_dots(col = "elev", size = .2, palette="plasma", legend.is.portrait = FALSE, title = "") +
tm_layout(legend.width = 1, legend.outside = TRUE, legend.outside.position = "bottom")
```

![screenshot from 2018-07-12 15-29-56](https://user-images.githubusercontent.com/2444081/42636205-76b0844c-85e8-11e8-8ef1-9f8f0a7f0fc3.png)

Not really satisfied by the spacing. The space between dots and labels is quite large, because it is determined by the original `legend.text.size`, and not the decreased text size (it is decreased to prevent overlap). You can play with `legend.text.size` to see this.

**Comment by jannes-m** [comment]
Ok, thanks for the clarification!
