### ISSUE TITLE
tm_raster - a number of pixels plotted

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#235]
`tm_raster()` is fast for small and medium-sized rasters (see the last example). 
However, it is not so good for large ones (>few millions of pixels) - then it takes a long time (and an enormous part of RAM) to make a plot.
Is it possible to add a new argument similar to `maxpixels` in **rasterVis**?

``` r

# prepare data ------------------------------------------------------------
library(raster)
r = raster(nrow = 1000, ncol = 1000, vals = sampleInt(10, 1e+6, replace = TRUE))

# rasterVis ---------------------------------------------------------------
library(rasterVis)
system.time(print(levelplot(r, maxpixels = 1e6)))
```

![](https://i.imgur.com/qhgA781.png)

    #>    user  system elapsed 
    #>   5.744   0.103   5.937
    system.time(print(levelplot(r, maxpixels = 1e4)))

![](https://i.imgur.com/ri1OKzv.png)

    #>    user  system elapsed 
    #>   0.506   0.005   0.517
    system.time(print(levelplot(r, maxpixels = 1e1)))

![](https://i.imgur.com/dCvoBTC.png)

    #>    user  system elapsed 
    #>   0.093   0.000   0.094
    
    # tmap --------------------------------------------------------------------
    library(tmap)
    system.time(print(tm_shape(r) + tm_raster()))
    #> Linking to GEOS 3.6.1, GDAL 2.2.4, proj.4 4.9.3

![](https://i.imgur.com/TPHBoS0.png)

    #>    user  system elapsed 
    #>   0.499   0.028   0.530

Created on 2018-07-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mtennekes** [comment]
Definitely a great idea!

The implementation is not as straightforward as it may sound. Currently the processing of raster objects is: 

1. determine type of raster data
2. reproject if necessary
3. extract and preprocess raster data (e.g. use color tables, and fix factor levels if step 2 is applied)
4. process raster data (apply class intervals etc.)
5. plot the raster object

It would make sense to apply the aggregation between 2 and 3. However, this would influence the result of step 4, i.e. the class intervals may be different.

**Comment by tim-salabim** [comment]
Different from what? The original that was passed in, or the one you see in the plot. I think it is more important that things are coherent within the plot. A suitable warning that you are messing with the data should be enough for the user (this is something that caught me multiple times when working with raster plots - as there is no warning).

Just to provide some perspective, in mapview we do it between 1. and 2. using [this](https://github.com/r-spatial/mapview/blob/d3e03dc8fad919a3620c65a8da51a260ab9c0974/R/leafletControls.R#L165) function. Whether it is done before reprojection does not matte I think, but it should definitely happen before any color creation etc. Additionally, reprojection takes a lot longer for large rasters, that's why we opted to sample first...
