### ISSUE TITLE
Lots of outer margin despite outer.margins=0

### ISSUE THREAD

**Issue by aloboa** [mtennekes/tmap#250]
I get a lot of outer margin despite specifying outer.margins=0
This is particularly inconvenient for rmarkdown (see Rmd file in https://www.dropbox.com/s/3963dm2mx9g9ilp/tmaptest2_log.Rmd?dl=0)
which I process with
`rmarkdown::render("tmaptest2_log.Rmd", html_document(toc=TRUE,toc_float = TRUE, code_folding = "hide", keep_md = TRUE))`

Any way to avoid the outter space?
Thanks
Agus

Reproducible example:
```
require(raster)
require(rgdal)
require(ggplot2)
require(tmap)

# dirtopo <- "../GEODATA/TOPO"
# topo <- brick(file.path(dirtopo,"2005_IslaDecepcion_TOPO.jpg"))
# projection(topo) <- CRS("+init=epsg:32720")
# topocoarse <- aggregate(topo,fact=10)
# writeRaster(topocoarse,file="topocoarse",format="GTiff",dataType="INT1U")
download.file("https://www.dropbox.com/s/731d8l3mdditpev/topocoarse.tif?dl=1",
              destfile="topocoarse.tif",
              method="auto")
topocoarse <- brick("topocoarse.tif")
test <- sampleRandom(topocoarse,100,sp=TRUE)
test@data <- round(test@data)
names(test@data) <- paste0("V",1:3)
test@data$Source <- rep(LETTERS[1:4],rep(25,4))
head(test@data)
summary(test@data)

m <- tm_shape(topocoarse) +
    tm_rgb() +
    tm_shape(test) +
    tm_bubbles(size="V1",style="cont",col="V2",
                          palette="-RdYlBu",border.alpha =0) +
    tm_facets(by="Source",ncol=2, free.coords=FALSE) +
    tm_layout(main.title="DEM - GPS",
              legend.outside=TRUE, legend.outside.position="bottom",
              legend.stack="horizontal", outer.margins=0)
m
tmap_save(m, "tmaptest2.png", height=12)
```

**Comment by mtennekes** [comment]
Thanks for asking. Unfortunately, I get this error:

```r
topocoarse <- brick("topocoarse.tif")
# Error in .local(.Object, ...) : 
# 	TIFFReadDirectory:Cannot handle different values per sample for "SampleFormat"
# 
# Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
# 	Cannot create a RasterLayer object from this file.
```

I'm on currently on Windows. Also QGIS fails to load the tif file.

**Comment by aloboa** [comment]
Weird, just tried agin and it works here, also with qgis,
I send you an attachment to your gmail account
Agus

**Comment by mtennekes** [comment]
Thx!

The best way to deal with these issues is to set `design.mode = TRUE` (argument of `tm_layout`).

The argument that you are looking for is probably `legend.outside.size`. `outer.margins` controls the margins between the borders of the device and everything that is plotted. `legend.outside.size` controls the size of the legend when it is plotted outside the map. The higher this value, the smaller the map itself becomes. It is quite difficult to set a good default value for this parameter, since it depends on the font size, aspect ratio, and the height of the legend (i.e. the number of legend items).

If you have any suggestions how to improve it, or how to improve the docs, please let me know.

**Comment by aloboa** [comment]
Thanks. I get the figure wider by including `legend.outside.size=0.2,` but do not understand why.
Why a parameter regarding legend size has such an impact of the total width of the figure?
Also, it is stated in the help page:
"legend.outside.size	: Numeric value that determines the relative size of the legend,..."
relative size to what? After `legend.outside.size=.2` the legend is not 20% of the total width.

**Comment by mtennekes** [comment]
Could you give a reproducible example, with the figure itself, and with `design.mode = TRUE`?

**Comment by aloboa** [comment]
Is this ok?
http://diapiro.ictja.csic.es/alobo/blog/tmaptest3_log.html

**Comment by mtennekes** [comment]
Thx, now I understand the confusion.

When `legend.outside.position = "bottom"`, the `legend.outside.size` is the relative height (and not the width). So in your last plot, the height of purple box is (approx) 20% of the total height.

The width of the figure, and also the left- and right-hand side margins are a result of these settings and the aspect ratios. The aspect ratio of each facet is determined by the shape object (`topocoarse`). You can change this to the device by setting `asp = 0`. However, since your shape is a raster, the result is probably not what you are looking for:
![rplot01](https://user-images.githubusercontent.com/2444081/47602449-704f9c00-d9df-11e8-80ec-81934b5cfeab.png)

You may want to change the aspect ratio of the figure in order to decrease the left- and right-hand side margins, if that is what you are looking for.
