### ISSUE TITLE
Missing legend with legend.outside() and tm_raster()

### ISSUE THREAD

**Issue by MatthieuStigler** [mtennekes/tmap#254]
Hi

With `tm_raster()` having two layers (i.e. 2 colours), and using `tm_layout(legend.outside = TRUE)`, one of the legends disappears? Behaviour observed with both cran and dev version. 

Try:
```

library(tmap)

data(land)

tm_examp <- tm_shape(land) +
  tm_raster(c("cover_cls", "elevation")) 

tm_examp
tm_examp  +
  tm_layout(legend.outside = TRUE)
```

![rplot](https://user-images.githubusercontent.com/108840/47249550-9d8dc000-d3c9-11e8-8439-92afb9fe612b.png)

Thanks!

**Comment by mtennekes** [comment]
Thanks! Actually, this is by design. The outside legend is supposed to be for one map. When small multiples are used, the outside legend is taken from the first map only (assuming they are the same for each map, which is the case ).

I will think about solutions. At least, I will add a warning for this behaviour.

You can use `tmap_arrange` as a workaround:

```r
tmap_arrange(
  tm_shape(land) + tm_raster("cover_cls") + tm_layout(legend.outside = TRUE),
  tm_shape(land) + tm_raster("elevation") + tm_layout(legend.outside = TRUE)
)
```

**Comment by mtennekes** [comment]
Thanks! Actually, this is by design. The outside legend is supposed to be for one map. When small multiples are used, the outside legend is taken from the first map only (assuming they are the same for each map, which is the case ).

I will think about solutions. At least, I will add a warning for this behaviour.

You can use `tmap_arrange` as a workaround:

```r
tmap_arrange(
  tm_shape(land) + tm_raster("cover_cls") + tm_layout(legend.outside = TRUE),
  tm_shape(land) + tm_raster("elevation") + tm_layout(legend.outside = TRUE)
)
```

**Comment by mtennekes** [comment]
Actually, this is by design. When `outside.outside = TRUE`, tmap assumes the small multiples share the same legend. So, it actually takes the legend from the first map only.

I will think about a solution. Anyway, it is good to add a warning for this behaviour.

A workaround:

```r
tmap_arrange(
  tm_shape(land) + tm_raster("cover_cls") + tm_layout(legend.outside = TRUE),
  tm_shape(land) + tm_raster("elevation") + tm_layout(legend.outside = TRUE)
)
```

**Comment by mtennekes** [comment]
Yes, because the outside legend is not meant to be used with facets where each facet has its own legend.
