### ISSUE TITLE
Pass dataPrecision to classIntervals to control decimals in legend breaks?

### ISSUE THREAD

**Issue by mbacou** [mtennekes/tmap#26]
Hi, just wondering if there is a way to control the number of significant and displayed decimals in legend breaks (without needing to pass breaks manually). Would passing dataPrecision argument to classIntervals() be an option?
Thx for a great package.

**Comment by mtennekes** [comment]
Hi Melanie, thanks for your nice question. The arguments `legend.digits` and `legend.scienfitic` in `tm_layout` are closely related.

It would indeed be nice to have an `legend.decimals` argument as well. Moreover, it would make more sense to have there arguments available in the layer function, since layers may need different settings.

**Comment by mbacou** [comment]
Thanks, I had overlooked the `tm_layout` arguments. These will work in most cases. You're right that these should ideally be passed to the layer function instead.

**Comment by mtennekes** [comment]
FYI, I rearranged the formatting options. Now there is a `legend.format` in `tm_layout` (global) and in each layer function. It takes a list consisting of formatting options like the number of digits.
Notice that `digits` is the number of decimals if `scientific=FALSE` or `format="f"`

**Comment by mbacou** [comment]
Thanks, perfect!
