### ISSUE TITLE
How to make tm_symbols show on single map?

### ISSUE THREAD

**Issue by Robinlovelace** [mtennekes/tmap#308]
I suspect this is easy to fix, and I may have missed something in the documentation, but I cannot work out how to make a map in which the number of icons is equal to the number of points. Reproducible example:

``` r

# minimal example:
library(tmap)
p = spData::nz_height[1:2, ]
i = magick::image_read(system.file("img/airplane.png", package = "tmap"))
magick::image_write(i, "icon1.png")
magick::image_write(magick::image_scale(i, "20x20"), "icon2.png")
icons = tmap_icons(file = c("icon1.png", "icon2.png"))
tm_shape(p) +
  tm_symbols(shape = icons)
```

![](https://i.imgur.com/7ENKTnT.png)

<sup>Created on 2019-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Context: I'm working on ways to automatically create a photomap, a little like [this](https://www.sigterritoires.fr/index.php/en/geotag-and-import-photos-replace-photo2shape-in-qgis-2/), which could one day become a package.

Example code (not reproducible):

```r
# Aim: make a photosmap

photos_files = list.files(path = "~/Pictures/2019/05/24/", pattern = ".jpg", full.names = TRUE)
photos_info = exifr::read_exif(photos_files)
photos_sf = sf::st_as_sf(photos_info, coords = c("GPSLongitude", "GPSLatitude"), crs = 4326)
plot(photos_sf$geometry)

mapview::mapview(photos_sf)


make_logo = function(f, geometry = "100x100") {
  magick::image_scale(
  image = magick::image_read(f),
  geometry = geometry
  )
}

make_logos = function(f, geometry = "100x100") {
  images = lapply(f, make_logo, geometry = geometry)
}

save_logos = function(f, geometry = "100x100") {
  f_logo = paste0(gsub(pattern = ".jpg", replacement = "", x = f), "_logo.png")
  i_list = make_logos(f, geometry = "100x100")
  purrr::map2(i_list, f_logo, magick::image_write, format = "png")
  f_logo
}

i_list = make_logos(photos_files[1:2])
i_list[[2]]


i = photos_files[3:5]
logo_paths = save_logos(i)
tmap_mode("view")
icons = tmap::tmap_icons(file = logo_paths)
photos_sf$url = icons$iconUrl
tmap::tm_shape(photos_sf[3:5, ]) +
  # tmap::tm_dots() +
  tmap::tm_symbols(shape = icons) +
  tm_facets(ncol = 1, nrow = 1)
tmap::tm_logo()

```

**Comment by mtennekes** [comment]
I understand the confusion. The thing is that `shape` is an aesthetic, similar to `col`: it is either a variable name or a fixed value. If it is specified with more than one value, small multiples will appear. This happened in your example, but also in:

```r
data(metro)
tm_shape(metro) +
	tm_symbols(col = c("blue", "green"))
```
![Rplot](https://user-images.githubusercontent.com/2444081/58380719-f4d5bd80-7fb4-11e9-8587-ef45c51c959d.png)

If the want an icon for each data point, the way to go is to create a categorical variable with one unique category per point, and use the argument `shapes` to assign the icons. Note that `shapes` is similar to `palette`.

```
icons = tmap_icons(file = c(system.file("img/airplane.png", package = "tmap"),
							system.file("img/city.png", package = "tmap")))
p$cat <- factor(1:2)
tm_shape(p) +
	tm_symbols(shape = "cat", shapes = icons)
```

![Rplot02](https://user-images.githubusercontent.com/2444081/58380766-631a8000-7fb5-11e9-9fc0-41a722b6cd54.png)

Also note that I used another icon rather than a smaller airplane, since tmap resizes the icons to a standard size.

If you have suggestions how to improve the docs, let me know!

**Comment by Robinlovelace** [comment]
Many thanks @mtennekes that makes sense. I've made progress using `leaflet()` but suspect it may be worth adding a `photomap_tmap()` function at some point: https://github.com/Robinlovelace/photomapr

One to discuss when we meet in July perhaps!
