### ISSUE TITLE
unable to adjust legend width

### ISSUE THREAD

**Issue by romunov** [mtennekes/tmap#312]
A user [reported on SO](https://stackoverflow.com/questions/56404181/adjusting-legend-size-in-tmap) that he or she is unable to adjust the width of an (outside) legend.

No matter how I adjust the `legend.width` nothing happens. Can you shed any light on the matter?

```
library(tmap)
data(land)

tm_shape(land, projection = "robin", is.master = TRUE) + 
  tm_raster("elevation", legend.is.portrait = FALSE, style="cont", midpoint = NA, 
            palette = terrain.colors(50)) + 
  tm_layout(earth.boundary = TRUE, legend.outside = TRUE, legend.outside.position = "bottom", frame = FALSE,
            legend.width = 10)  # modified this value ranging from 0.5 to several 100
```

**Comment by mtennekes** [comment]
Yes. Perhaps a bit unclear, so we may want to improve the docs a bit.

When `legend.outside = FALSE`, it functions as follows:

* The content of the legend will have some width, based on the content of the legend itself, and on parameters such as `legend.text.size`. Let me call this the *normal legend width*.
* `legend.width` is a a threshold value. When the normal legend width is smaller than `legend.width`, nothing happens, but when it is larger, the content of the legend will be shrunk by decreasing the font sizes and omitting labels if needed.

When `legend.outsize = TRUE`, `legend.width` will be set to .9, which basically means the whole page width. Why? Because there is no reason to shrink the legend width, since there is enough space.

Let me know what kind of legend you want to achieve.

**Comment by Nowosad** [comment]
@romunov please reopen the issue if you still have any questions.

**Comment by FVFaleiro** [comment]
@mtennekes, I did not understand your comment because when `legend.outsize = TRUE` the legend is not adjusted to 90% of the graphs when ploted in the horizontal as in the below code. The legend is about 30% of the available space. @mtennekes and @romunov, Could you provide an example to increase the legend?

```
r <- raster::raster(matrix(runif(100), 10, 10))
tm_shape(r) +
  tm_raster(legend.is.portrait = FALSE, style = 'cont', title = '', palette = "-RdBu",
         breaks = pretty(cellStats(r, range), 10), legend.reverse = F) +
  tm_layout(frame = FALSE, legend.outside = TRUE, legend.outside.position = "bottom")
```

**Comment by mtennekes** [comment]
Let me quote myself: "When the normal legend width is smaller than legend.width, nothing happens". See also https://github.com/mtennekes/tmap/issues/367

**Comment by FVFaleiro** [comment]
@mtennekes your quote is for legend.outside = FALSE, the precise quote I was mentioning is: "When **legend.outsize = TRUE**, legend.width will be set to **.9**, which basically means the whole page width. Why? Because there is no reason to shrink the legend width, since there is enough space."
However the #367 make me understand that there is not implemented yet.

> You give this advice: "Not possible yet. A hacky workaround is to increase the legend font size (legend.text.size = 25), and use the grid package to change the font size of the labels back to normal." 
The code below have the result following the first part of you advice, but I do not know how use the grid package to change the font size: 
```
library(tmap)
library(raster)
r <- raster(matrix(runif(100), 10, 10))
tm_shape(r) +
  tm_raster(legend.is.portrait = FALSE, style = 'cont', title = '', palette = "-RdBu",
         breaks = pretty(cellStats(r, range), 10), legend.reverse = F) +
  tm_layout(frame = FALSE, legend.outside = T, legend.outside.position = "bottom", legend.text.size = 25)
```

**Comment by mtennekes** [comment]
@FVFaleiro In your example, the legend is not shrinked, but drawn normally. The parameter `legend.width` only makes sure that the legend is not larger than some threshold. For `legend.outsize = TRUE` this threshold value is 0.9 which means the whole page minus some margins.

Not sure how to make this more clear (also in the docs)...
