### ISSUE TITLE
tmap_leaflet add.titles option does not produce visible title

### ISSUE THREAD

**Issue by francisbarton** [mtennekes/tmap#314]
I have a tmap constructed like this:
```
density_map <- 
  tm_shape(ef_geom_data, name = "Population density") +
  tm_polygons(col = "density",
              title = "Density (people/ha)"
              ... etc) +
  tm_layout(main.title = "Population density by OA")
```
If I run
`print(density_map, mode = "plot", show = TRUE, add.titles = TRUE)`
(or just `density_map`)
I get a nice plot with my title (`main.title`) displayed above.
If I run
`tmap_leaflet(density_map, mode = "view", show = TRUE, add.titles = TRUE)`
I also get a lovely interactive leaflet map as desired, with a legend and controls... but no title to be seen anywhere.
What do I need to do to get `tmap_leaflet` to add my title to the map?
I have looked through the various options that `leaflet` itself provides, to see if I could add the title by piping the above command to `leaflet`, but I didn't see a `leaflet::AddTitle` option or anything similar.

**Comment by mtennekes** [comment]
If you use `title` instead of `main.title`, the title should appear in view mode.

This is quite confusing (even for me), but the reason to have both `title` and `main.title` is that the former is the title for each single map, and the latter for the total plot, which may include small multiples. 

Only `title` is implemented in view mode.

If you have suggestions how to improved the docs, let me know.
