### ISSUE TITLE
tm_graticules() does not work for some cases

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#333]
...I've added my workaround below.

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(tmap)
library(spData)

world_laea1 = st_transform(world, 
                           crs = "+proj=laea +x_0=0 +y_0=0 +lon_0=0 +lat_0=0")

# fails -------------------------------------------------------------------
tm_shape(world_laea1) +
  tm_graticules() +
  tm_borders(col = "black")
#> Error in st_coordinates.sfc(st_geometry(x)): not implemented for objects of class sfc_GEOMETRY
```

``` r

# works -------------------------------------------------------------------
world_laea1_g = st_graticule(ndiscr = 10000) %>%
  st_transform("+proj=laea +x_0=0 +y_0=0 +lon_0=0 +lat_0=0") %>% 
  st_geometry()

tm_shape(world_laea1_g) +
  tm_lines(col = "gray") +
  tm_shape(world_laea1) +
  tm_borders(col = "black")
```

![](https://i.imgur.com/VcktpdN.png)

<sup>Created on 2019-07-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
This was a nasty one. The error came from the grid labels, which are very hard to draw.

I've added two arguments to be able to reproduce the sf plot: `labels.show` and `ndiscr`:

```r
tm_shape(world_laea1, bbox = c(-12.5e6, -12.5e6, 12.5e6, 12.5e6)) +
	tm_graticules(n.x = 20, n.y=10, labels.show = FALSE, ndiscr = 1000) +
	tm_borders(col = "black")
```
![Rplot01](https://user-images.githubusercontent.com/2444081/62784295-791ce480-babe-11e9-82ef-45f4e8431f23.png)

**Comment by Nowosad** [comment]
Thanks @mtennekes - it works now for the projection above. 
I found another border case:

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(tmap)
library(spData)

world_moll = st_transform(world, crs = "+proj=moll")
tm_shape(world_moll) +
        tm_graticules(labels.show = FALSE, ndiscr = 1000) +
        tm_borders(col = "black")
#> Warning in min(min(grid.x2), bbx[1], na.rm = TRUE): no non-missing
#> arguments to min; returning Inf
#> Warning in max(max(grid.x2), bbx[3], na.rm = TRUE): no non-missing
#> arguments to max; returning -Inf
#> Warning in min(min(grid.y2), bbx[2], na.rm = TRUE): no non-missing
#> arguments to min; returning Inf
#> Warning in max(max(grid.y2), bbx[4], na.rm = TRUE): no non-missing
#> arguments to max; returning -Inf
#> Error: $ operator is invalid for atomic vectors
```

![](https://i.imgur.com/skr5LGU.png)

<sup>Created on 2019-08-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
This one has some problems with the projection:

```r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
library(spData)
#> To access larger datasets in this package, install the spDataLarge
#> package with: `install.packages('spDataLarge',
#> repos='https://nowosad.github.io/drat/', type='source')`

world_moll <- st_transform(world, crs = "+proj=moll")
world_moll_longlat <- st_transform(world_moll, crs= "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0")
st_is_valid(world_moll_longlat)
#>   [1]    NA  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [12]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE    NA  TRUE  TRUE  TRUE
#>  [23]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [34]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [45]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [56]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [67]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [78]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [89]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [100]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [111]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [122]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [133]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [144]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [155]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [166]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [177]  TRUE
plot(world_moll_longlat)
#> Warning: plotting the first 9 out of 10 attributes; use max.plot = 10 to
#> plot all
#> Error in CPL_geos_is_empty(st_geometry(x)): Evaluation error: IllegalArgumentException: Invalid number of points in LinearRing found 3 - must be 0 or >= 4.
```

The same error appears when I plot `world_moll` in view mode (since the same transformation is applied). However, it works with mapview. So maybe there is a workaround for that.

**Comment by Nowosad** [comment]
Is going through WGS84 necessary? This works using the base plot:

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(spData)

world_moll = world %>%
  st_transform("+proj=moll") %>% 
  st_geometry()
g = st_graticule(x = world_moll) %>% 
  st_geometry()
plot(world_moll)
plot(g, add = TRUE)
```

![](https://i.imgur.com/zhUCGny.png)

<sup>Created on 2019-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
The problem is that tmap uses some smart high-level things that use sf functions such as `st_centroid` and `st_is_empty`. Those functions may throw errors when the sf object is invalid.

`world` is valid, but `world_moll` is not.

What I just did, is a `st_is_valid` check for each used sf object, and fix it if needed with `lwgeom::st_make_valid`. However, there are two drawbacks:

1. `lwgeom` is required (so it will be place in imports rather than suggests). We can make a work around for this with `requireNamespace`.
2. `tmap` will be a tad slower. I did some benchmarking, and tmap is normally 1.5 times slower than mapview, but with the additional validity check 1.75 times slower. The selling point of tmap is not the speed. In that sense, I regard mapview as a sports wagon (light-weight and early adaptor) and tmap as a (hopefully) solid truck. However, the faster the better, especially when using it in shiny apps.

Any thoughts on this? @Robinlovelace @timsalabin @rsbivand @edzer

**Comment by edzer** [comment]
@timsalabim

**Comment by tim-salabim** [comment]
**mapview** doesn't do anything to check or ensure transformed features are valid:

https://github.com/r-spatial/mapview/blob/74d745d24ef1b1f821a018f4902831dd5247a79d/R/projection.R#L112

**leaflet** does not seem to have any problems with non-valid features:

```r
library(sf)
library(spData)
library(mapview)
library(leaflet)

world_moll = world %>%
  st_transform("+proj=moll") %>% 
  st_geometry()

leaflet() %>%
  addTiles() %>%
  addPolygons(data = st_transform(world_moll, 4326))
```

I think for **mapview** it wouldn't make sense to `st_make_valid` any features, as sometimes the intention is to view and inspect these invalid geometries. What would be helpful though is a check along the lines of:

```r
which(!st_is_valid(st_transform(world_moll, 4326)) | is.na(st_is_valid(st_transform(world_moll, 4326))))
# [1]   1  19 160
```

@mtennekes I agree that for **tmap** an effort should be made to repair geometries, but that's obviously a matter of scope.

Also, invalid geometries are first introduced in `st_transform(world, "+proj=moll")` as 
```r
st_is_valid(world_moll)
[1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [14]  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [27]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [40]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [53]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [66]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
 [79]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [92]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[105]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[118]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[131]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[144]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[157]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[170]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

idx = which(!st_is_valid(world_moll) | is.na(st_is_valid(world_moll)))
mapview(world_moll[idx], native.crs = TRUE)
```

![Screenshot from 2019-08-20 11-05-44](https://user-images.githubusercontent.com/2826432/63333883-7f228900-c33a-11e9-8ce3-7698ef913f19.png)

though it's not exactly the same features that are invalid in `world_moll_longlat`. But I guess that's why **tmap** also fails in plot mode.

In any case, an interesting edge case.

**Comment by mtennekes** [comment]
Thanks @tim-salabim 

For the time being, I added the st_is_valid check for each `sf` object. When people start to complain about computation speed, we can open a new issue for that:-)
