### ISSUE TITLE
Error with PROJ6 and GDAL3

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#387]
The attached code works with a warning with PROJ5 and GDAL2, but gives an error for PROJ6 and GDAL3.
I am using the following docker for testing - https://hub.docker.com/r/jakubnowosad/rspatial_proj6.

``` r
# remotes::install_github("mtennekes/tmaptools")
# remotes::install_github("mtennekes/tmap")
library(spData)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
library(tmap)

world_laea2 = st_transform(world,
                           crs = "+proj=laea +x_0=0 +y_0=0 +lon_0=-74 +lat_0=40")

  tm_shape(world_laea2) + tm_borders(col = "black")
#> Warning: The shape world_laea2 is invalid. See sf::st_is_valid
#> Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 177, 184
```

<sup>Created on 2020-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
It works on PROJ 6.2.1.

The problem was a geometry collection split: after transformation Antarctica is a set of polygons and a line, an artifact of the transformation which probably didn't happen in older PROJ versions.

The bug was in the internal function `split_geometry_collection`. Still have to test it in other cases. If needed, we can reopen this issue.

**Comment by Nowosad** [comment]
:+1: thanks Martijn! I will let you know if there are other issues somewhere.
(CC: @Robinlovelace)

**Comment by Robinlovelace** [comment]
Great work as always @Nowosad and @mtennekes you guys are 🔥  and when your powers combine 💥
