### ISSUE TITLE
Are there plans to generalise download of raster tiles to make more tilesets available?

### ISSUE THREAD

**Issue by Robinlovelace** [mtennekes/tmap#39]
Not sure if this is the right place to be asking this.

But I'm wondering if there is a way to include a wider range of base maps, e.g. by using leaflet's trick of allowing the base url to be set: https://rstudio.github.io/leaflet/basemaps.html

Completely understand the desire to use mostly open data - there are more available here: http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames .

Other than a general interest in this question I'm wondering about methods for accessing before/after imagery. Automating that could be really useful, e.g. for identifying poor management practice which increases flooding, as illustrated by the Google Earth imagery here: http://www.theguardian.com/commentisfree/2015/dec/29/deluge-farmers-flood-grouse-moor-drain-land

Also for @dkahle are there any plans for generalising `get_map` to include more tileservers? Notice that [`get_navermap`](https://github.com/dkahle/ggmap/blob/master/R/get_navermap.R) is quite new.

Sorry this question is so broad and potentially off-topic.

**Comment by mtennekes** [comment]
Thanks for your question, which is certainly not off-topic. Currently, `tmap` relies on `OpenStreetMap` to get OSM tiles, because it was easy to embed. However, since the problems its dependencies (see https://github.com/mtennekes/tmap/issues/37), I had to suggest instead of import the package. Not an ideal solution, so I'm open to improvement.

I noticed the output of `get_map` is clean and well organized. I could easily write a `tmap` wrapper around it. The downside is that `ggmap` has quite a lot of dependencies to be imported by tmap. 

To get to your question of the inclusion of more tileservers. Maybe we could start a new, lightweight, package just to get tiles.

**Comment by Robinlovelace** [comment]
Your suggestion sounds good. However, even that does not seem as simple as expected (for me at least!).

Here is an example of how OpenLayers does it: http://openlayers.org/en/v3.5.0/examples/wms-tiled.html

And here's a single jpeg file: http://oatile1.mqcdn.com/tiles/1.0.0/sat/15/5240/12661.jpg

Not sure how to pull the 'right' files like that for a generic area/zoom and suspect an interface to Leaflet, e.g. via v8, may be the best way. But that ain't simple either and leaflet is another (lightweight) dependency...

**Comment by Nowosad** [comment]
https://github.com/riatelab/maptiles or https://github.com/hypertidy/ceramic are my current tools (2021) for this kind of problems
