### ISSUE TITLE
Getting Esri.WorldTopoMap tiles to show not working as expected

### ISSUE THREAD

**Issue by zross** [mtennekes/tmap#414]
Hi Martijn, I found a way around this (see bottom) so you can ignore until you have time but I'm finding that getting Esri.WorldTopoMap to show is not working as I expected and, oddly, if you spell a tile layer name wrong in `tm_tiles()` it seems to render all three basemap tile sets on top of each other (?).

I tried this first:

```r
library(tmap)
data(World, metro)

tmap_mode("view")
tm_shape(metro) +
  tm_tiles("Esri.WorldTopoMap") +
  tm_bubbles("pop2010", col = "pop2010")
```

But I get Esri.WorldGrayCanvas instead:

![image](https://user-images.githubusercontent.com/1395177/79371296-2388b980-7f22-11ea-9ca1-8f43dd5cddaa.png)

In playing around I tried this:

```r
tmap_mode("view")
tm_shape(metro) +
  tm_tiles("Esri.x") +
  tm_bubbles("pop2010", col = "pop2010")
```

And very oddly it seems to render all three of the basemap tiles sets on top of each other (?):

![image](https://user-images.githubusercontent.com/1395177/79371237-0bb13580-7f22-11ea-8586-d3351d413f56.png)

Then I used

```r
tmap_options(basemaps = "Esri.WorldTopoMap")
tm_shape(metro) +
  tm_bubbles("pop2010", col = "pop2010")
```

And this gave me what I wanted:

![image](https://user-images.githubusercontent.com/1395177/79371616-a578e280-7f22-11ea-9aef-84b0c112d5d5.png)

**Comment by mtennekes** [comment]
Thanks Zev! I think this is an issue of improving the docs (note to self)

The thing is that `tm_tiles` is meant to be used for *overlays*, and `tm_basemap` for basemaps. 

**First map**

That is why you still see the three default basemaps (determined by tmap option basemaps) in your first map:
![Screenshot from 2020-04-16 10-15-33](https://user-images.githubusercontent.com/2444081/79431857-4e7b1800-7fcb-11ea-9e6a-508bda72c9c7.png)

**Second map**

This is a bug caused by leaflet: if the layer-provider name is invalid (i.e. it does not occur in leaflet::providers), than `leaflet::addProviderTiles` doesn't throw errors or warnings. Moreover, the function `leaflet::addLayersControl` fails subsequently, since the invalid tile layer cannot be found. Not sure how to handle this. Previously, I tried to re-export `leaflet::providers` in `tmap` but this object is not exported by `leaflet`.

** Third map**

Similar to:

```r
tm_basemap("Esri.WorldTopoMap") +
tm_shape(metro) +
    tm_bubbles("pop2010", col = "pop2010")
```

**Comment by zross** [comment]
Ah, I guess the distinction between tiles and overlays was lost on me! I also don't know how one would address the issue of rendering three different tilesets. Thanks for the quick response and clarifications!

**Comment by Nowosad** [comment]
@zross should be close this issue?

**Comment by zross** [comment]
Yes I think it can be closed.
