### ISSUE TITLE
Simple objects are not plotted correctly (one vs two points)

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#420]
``` r
# remotes::install_github("mtennekes/tmaptools")
# remotes::install_github("mtennekes/tmap")
library(tmap)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
two_points = c(st_point(c(1877389, -1860123)),
               st_point(c(2080971, -1860123)))

two_points = st_sf(geom = st_sfc(two_points), crs = 2163)

# one point only
tm_shape(two_points) + 
  tm_dots(size = 5)
```

![](https://i.imgur.com/MaHSHp8.png)

``` r

# works
tmap_mode("view")
#> tmap mode set to interactive viewing
tm_shape(two_points) + 
  tm_dots(size = 5)
```

![](https://i.imgur.com/qHp2h9f.png)

<sup>Created on 2020-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
It is fixed with the latest tmap AND tmaptools versions. The problem occurred when a bounding box has height and/or width 0. In `tmaptools::bb`, I've added an argument `asp.limit`, which makes sure that the aspect ratio of the map is set between 1/asp.limit and asp.limit. In tmap, I've set this by default to 10, but it can be changed via `tm_shape` (arguments are pased on to `bb`).
