### ISSUE TITLE
Add Parameters to control line width breaks and styles 

### ISSUE THREAD

**Issue by xiaofanliang** [mtennekes/tmap#433]
```r
library(tmap)
data(rivers)

tm_shape(rivers) +
  tm_lines(col="black", lwd="strokelwd", scale=2, 
           legend.lwd.show = TRUE)`
```
<img width="530" alt="Screen Shot 2020-04-30 at 11 17 27 AM" src="https://user-images.githubusercontent.com/22874361/80728544-0c76c980-8ad5-11ea-8a14-dde4ba3c46e9.png">

This is what the default example looks like with rivers data. I am not sure how the breaks are defined (quantile? equal interval?). I tried to define the line width myself and used the codes below: 

```r
rivers = rivers %>% mutate(newlwd = case_when(
  strokelwd >= 1.5 & strokelwd <= 2.0 ~ 0.5,
  strokelwd > 2.0 & strokelwd <= 2.5 ~ 1,
  strokelwd > 2.5 & strokelwd <= 3.5 ~ 1.5,
  strokelwd > 3.5 & strokelwd <= 12 ~ 2
))

tm_shape(rivers) +
  tm_lines(col="black", lwd="newlwd", scale=2, 
           legend.lwd.show = TRUE)`
```
<img width="527" alt="Screen Shot 2020-04-30 at 11 17 48 AM" src="https://user-images.githubusercontent.com/22874361/80728765-4cd64780-8ad5-11ea-8a86-6d6deba31a4e.png">

The breaks for lwd are puzzling to me. I do not know how they are defined and there are no parameters to change them. The "breaks" and "style" arguments in tm_lines() only serve the "col" argument, but not the "lwd" argument. Can you add similar controls to "lwd" argument or a workaround? It is important to control the line width in spatial network maps to represent the volume of flows. Thanks!

**Comment by mtennekes** [comment]
Thanks for bringing this up!

There is a simple (and in most cases effective) method to determine the breaks of line widths: pretty(x, n = 7) with the second last and the fourth last element removed. In most cases, this is quite effective, because an increasing interval is generally more useful to show different widths, and the numbers are still rounded. For bubble sizes, a similar method is used, but with n=5 since bubbles are generally much wider than lines. Afterwards, the legend width is taken into account; if the legend with lines / bubbles is too wide (you can test this with setting `scale = 10`), the largest lines/bubbles are not shown in the legend.

If users want to change that, it can be done manually with the argument `lwd.legend`. For example `tm_shape(rivers) + tm_lines(lwd="strokelwd", scale=2, lwd.legend = c(0.5, 1.5, 2.5, 12))`. 

So far, I didn't see the need to implement different methods to determine the breaks. Why? Mainly because in contract to the color breaks, the line width/bubble size breaks only affect the legend, not the lines/bubbles in the map. Manual control over the line widths/bubble sizes in the legend (as shown above) should be sufficient for most users.

If you have any ideas how to improve this, please let me know.

**Comment by xiaofanliang** [comment]
Perfect! lwd.legend is what I was looking for. Thanks for the reply. I did not know this argument exists because I was looking at https://www.rdocumentation.org/packages/tmap/versions/0.7/topics/tm_lines for parameter documentation. https://cran.r-project.org/web/packages/tmap/tmap.pdf has complete documentation which includes the lwd.legend parameter.

**Comment by xiaofanliang** [comment]
Perfect! lwd.legend is what I was looking for. Thanks for the reply. I did not know this argument exists because I was looking at https://www.rdocumentation.org/packages/tmap/versions/0.7/topics/tm_lines for parameter documentation. https://cran.r-project.org/web/packages/tmap/tmap.pdf has complete documentation which includes the lwd.legend parameter.
