### ISSUE TITLE
qtm() fails on raster with on only a single value an NA

### ISSUE THREAD

**Issue by behrica** [mtennekes/tmap#44]
I have a raster object which values or only 1 and NA.
tmap fails to render this wit-:

Error in classIntervals(x, n, style = style) : single unique value
 
```    
 x=raster(ncol=2,nrow=2)
values(x) <- c(NA,1,1,NA)
plot(x)
qtm(x)

```
plot works, while qtm fails.

By replacing NA with 0, it works as well.
But I get the the raster from a file with the NA present, so I suppose it should work as well here.

**Comment by mtennekes** [comment]
Thanks for reporting this! The problem was that numeric styles (from the package classInt) didn't work with single unique values. Interpreting the values as categorical, i.e., `qtm(x, raster.style="cat")` does work. From now on, if there is a single unique value (besides `NA`), the style will be set to `"cat"`.
