### ISSUE TITLE
Manejo de Leyendas con Tmap

### ISSUE THREAD

**Issue by EDGAR-BARAHONA** [mtennekes/tmap#444]
Buena Noche, estoy intentando generar un mapa en base a la superposición de varios SHP (puntos y polígonos), en este caso primero genero la leyenda para los puntos y después  con "tm_add_legend", agrego las salidas de los archivo tipo polígono pero en este caso los label asociados a los poligonos quedan mas pequeños con referencia a los label de los puntos. EN SI QUISIERA QUE EL TAMAÑO DE TODOS LOS ELEMENTOS EN LA LEYENDA SEA EL MISMO.  Gracias

**Codigo Tmap**
```
ZH<-readOGR(dsn = "C:/EDGAR/PASAR/insumos/zonificacion/zonificacion", layer="ZH_E")

House.Points <-SpatialPointsDataFrame(BASE[,c("longitud","latitud")], BASE, proj4string = CRS("+init=EPSG:4326"))


tm_shape(House.Points) + tm_dots(col= "estación" , size=0.1)+tm_shape(ZH)+tm_borders(col="red", lwd = 1.5)+
  tm_shape(dep)+tm_borders(col = "Black")+tm_scale_bar(width = 0.22, position = c("right", "top"))+tm_grid(lines = FALSE)+
  tm_xlab("Longitud") +tm_ylab("Latitud") + tm_compass() +tmap_options(max.categories = 42,output.dpi = 600, output.format = "png") +
  tm_layout(title = "Leyenda",
            legend.outside = TRUE,
            legend.text.size = .8,
            legend.title.size =1,
            legend.outside.position = "right",
            main.title = "Estaciones Zona Estudio",
            main.title.position = "center",, 
            inner.margins = c(.02,.02,.02,.18),
            legend.frame = TRUE)+ tm_add_legend(type = c("line"),labels = "LIMITE CUENCA HIROGRAFICA",
                                                col = "red", lwd = 2, lty = 2.5, title = "Areas Geograficas")+
                                  tm_add_legend(type = c("line"),labels = "LIMITE DEPARTAMENTAL",col = "black", lwd = 1, lty = 1.5)
```
![image](https://user-images.githubusercontent.com/65068285/81470508-b2e75c80-91b0-11ea-9af1-cd3b61ea0d90.png)

Igualmente quisiera saber si existe alguna manera de establecer un numero de columnas para la leyenda, es decir que se pueda visualizar en mas de una columna.

Saludos Cordiales Desde Colombia.

**Comment by mtennekes** [comment]
Thanks for your question. I cannot reproduce it, so I can only guess (if you want a better answer, please provide a reproducible example).

The font size of the legend text is determined by the `tm_layout` argument `legend.text.size`, but it will shrink if there is not enough space either horizontally or vertically. In your case, the bottleneck is horizontal space, since your first legend is very long. It may seem as there is space left, but margins are taken into account. You can see all the margins and so by setting `design.mode = TRUE` in `tm_layout`.

I noticed that you have created two separate `tm_add_legend`s. You can make combime them  by providing a vector for `labels` and `col`. This will save space, and as a result, the labels will become larger.

Side note: you can only stack `tm_` functions. `tmap_` functions are stand-alone functions. `tmap_options` works like `options`: it sets the options for the session, and not just for one plot.

**Comment by EDGAR-BARAHONA** [comment]
Muchasimas Gracias.
