### ISSUE TITLE
Size defined in tm_symbols and tm_add_legend does not match up

### ISSUE THREAD

**Issue by xiaofanliang** [mtennekes/tmap#451]
I am trying to combine the size and color legend into one following this [post](https://github.com/mtennekes/tmap/issues/208). 

At the step where I need to manually define the size of symbols in `tm_add_legend`, I cannot correctly match the size used in `tm_symbols`.  I thought this line: `sizes.legend = c(1,2,4,8,12), scale=1` means that the sizes are scaled so that the maximum size is 1. Therefore, node that has log_size = 12 will have a point size of 1. Since `tm_add_legend` refers to the absolute point size, I normalize the number in sizes.legend by 12 to get their absolute point size. However, in the map below you can see that the node size from `tm_add_legend` does not really match up those from `tm_symbols`. 

Any idea why? How can I correct it so that the combined legend from `tm_add_legend` will have the same point size as the size legend? 

```r
library(tmap)
library(sf)
library(RColorBrewer)

data(World)
World$log_size = log(World$pop_est)

centroid = st_centroid(World)

tm_shape(World) + 
  tm_polygons() + 
  tm_shape(centroid) + 
  tm_symbols(col='pop_est', 
             style='quantile', 
             palette = 'YlOrRd',
             size='log_size', 
             sizes.legend = c(1,2,4,8,12),
             scale=1) + 
  tm_add_legend('symbol', col=brewer.pal(5, "YlOrRd"),
                size=c(1/12, 2/12, 4/12, 8/12, 12/12),
                labels = c('0-2 mln','2-6 mln','6-12 mln','12-33 mln','33-1339 mln'),
                title="Log Population Estimate"
                )
```
<img width="518" alt="Screen Shot 2020-05-24 at 5 37 06 PM" src="https://user-images.githubusercontent.com/22874361/82765510-843ec800-9de5-11ea-912e-bd5325cfa9dd.png">

**Comment by mtennekes** [comment]
The bubbles are not just normalized so that the maximum bubble has size 1.
What happens is here https://github.com/mtennekes/tmap/blob/master/R/process_size_aes.R#L101 is:

* The bubbles are by default rescaled to the maximum bubble value of the data (not of the legend). In this case, 21.0149. You can specify this maximum value with the argument `size.max`.
* The square root is taken since the area is proportional to the data, not the radius. (Empirical studies showed that the perceived proportional relation is not exactly the square root (power 0.5) but 0.5716. This can be enabled by setting `perceptual = TRUE`).


```r
tm_shape(World) + 
  tm_polygons() + 
  tm_shape(centroid) + 
  tm_symbols(col='pop_est', 
    style='quantile',
    palette = 'YlOrRd',
    size='log_size', 
    sizes.legend = c(1,2,4,8,12),size.max = 21,
    scale=1,legend.size.is.portrait = T) + 
tm_add_legend('symbol', col=brewer.pal(5, "YlOrRd"),
  size=(c(1,2,4,8,12)/21)^0.5,
  labels = c('0-2 mln','2-6 mln','6-12 mln','12-33 mln','33-1339 mln'),
  title="Log Population Estimate"))
```
![Rplot](https://user-images.githubusercontent.com/2444081/83111491-f4d73480-a0c4-11ea-9a88-5d693ad78aa4.png)

It would be good to document this somewhere with an example...

**Comment by mtennekes** [comment]
> It would be good to document this somewhere with an example...

Done! I've added a similar example in `tm_add_legend` and also improved the docs a bit. If something is unclear, please let me know.

**Comment by xiaofanliang** [comment]
Thanks!
