### ISSUE TITLE
Allow further customization of individual legends

### ISSUE THREAD

**Issue by martinschmelzer** [mtennekes/tmap#456]
I want to have the title, legend and imprint of my chart inside of one "box".
I achieved that stacking 3 seperate legends: 

    tm_add_legend(type = "text", title = "Map Title") +
    # legend automatically created by tm_fill
    tm_add_legend(type = "text", 
                title = "Additional information blabla, the date, copyright, blablabla")

This works but it would be nice to adjust 2 things:

1. There is blank space underneath the legend titles. How can I get rid of that, I actually just want to show the legend titles.

2. Adjust the font size of the legend title on a per legend basis.

Can that be done? Alternativley stacking `tm_credits` and legends would be nice. I just want all the information in one place.

**Comment by mtennekes** [comment]
I've done some improvements. 

`+ tm_add_legend(type = "title", title = "My title")` should also work. It does not add additional white space. You can run the code with `tmap_options(design.mode = TRUE)` in order to see all the margins.

Unfortunately, it is not possible to set font size per legend item.

If you have other questions, let me know. Please provide full reproducible examples, which will help me a lot.

**Comment by martinschmelzer** [comment]
Thanks for the improvements. I will give it a shot and see how far I can go with my modifications :)
