### ISSUE TITLE
Argument `title` not recognized in `tm_dots` when using the `size` aesthetic

### ISSUE THREAD

**Issue by martinschmelzer** [mtennekes/tmap#491]
Consider the following example:

```
data(World, land)

centroids <- sf::st_centroid(World)


tm_shape(World) + 
  tm_fill("pop_est_dens", style="kmeans", title="Population density") +
  tm_shape(centroids) +
  tm_dots(col = "pop_est", title="New Title")

tm_shape(World) + 
  tm_fill("pop_est_dens", style="kmeans", title="Population density") +
  tm_shape(centroids) +
  tm_dots(size = "pop_est", title="New Title")
```

In the first map, we successfully change the title of the legend for the tm_dots layer using the col aesthetic. When using size instead, it does not work.

**Comment by Nowosad** [comment]
Hi @martinschmelzer , you need to use `title.size` to change the size title in `tm_dots()`:

``` r
library(tmap)

data(World, land)

centroids <- sf::st_centroid(World)
#> Warning in st_centroid.sf(World): st_centroid assumes attributes are constant
#> over geometries of x

tm_shape(World) +
  tm_fill("pop_est_dens", style = "kmeans", title = "Population density") +
  tm_shape(centroids) +
  tm_dots(size = "pop_est", title.size = "New Title")
```

![](https://i.imgur.com/lRtXabl.png)

<sup>Created on 2020-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by martinschmelzer** [comment]
Oh boy. Ok that was not intuitive enough for me :D Thanks.

**Comment by mtennekes** [comment]
The intuition behind it is that `tm_symbols` has three aesthetics, `col`, `size` and `shape`, and a `title.<aes>` for each of them.
`tm_dots` is derived from `tm_symbols`, and is meant to be used with only the `col` aesthetic. Therefore, it is sufficient to have `title` as title argument (similar to `tm_fill`). The `size` and `shape` arguments can be changed, but shouldn't depend on data (otherwise it won't be a dot map anymore).

Let me know if it is clear now. We can improve the docs if needed.
