### ISSUE TITLE
view mode doesn't show titles

### ISSUE THREAD

**Issue by stragu** [mtennekes/tmap#524]
Facetting by one single column creates one facet per level of that variable. In plot mode, the values are used as titles for the panels. However, there are no panel titles in view mode.

```r
# get data
library(osmdata)
buildings <- opq(bbox = "west end, brisbane") %>% 
  add_osm_feature(key = "building") %>% 
  osmdata_sf() %>% 
  .$osm_polygons

library(tmap)
# static: shows panel titles (i.e. variable levels)
tmap_mode("plot")
tm_shape(buildings) +
  tm_polygons() +
  tm_facets(by = "wheelchair")
```

![image](https://user-images.githubusercontent.com/1747497/98458809-46412f00-21e0-11eb-8b2a-1d7d2dfc6f95.png)

```r
# interactive: no titles
tmap_mode("view")
tm_shape(buildings) +
  tm_polygons() +
  tm_facets(by = "wheelchair")
```

![image](https://user-images.githubusercontent.com/1747497/98458818-61ac3a00-21e0-11eb-8807-9b49e1037e1b.png)

Using:

- RStudio 1.3.1073
- R 4.0.3
- tmap 3.2

**Comment by paulsromer** [comment]
I think this is a more general issue, where titles no longer appear in view mode. 

I think this was caused by this update to print_tmap.R on Aug 11: https://github.com/mtennekes/tmap/commit/82f93a1c3ed0e574decb5bed112374c80e1286d5 
It'd be great if this functionality could come back. 

Title specified in the layout but no titles appear in view mode:
```r 
library("tmap")
data("NLD_muni")
tmap_mode("view"); 
tm_shape(NLD_muni) + 
	tm_dots(c("population"), size = "population") + 
	tm_layout(title = "Example Title")
```
![no_title](https://user-images.githubusercontent.com/34322683/99890111-39c5c900-2c19-11eb-9395-95be6bb3ca4a.png)

Using:

- R 4.0.3
- RStudio 1.3.1093
- tmap 3.2
- leaflet 2.0.3

**Comment by WimMertens** [comment]
Is this issue related with https://gis.stackexchange.com/questions/312580/tmaptm-facets-in-interactive-mode-in-html-r-markdown-file-small-multiples-v?

I run into exactly this problem.

**Comment by stragu** [comment]
Hi @mtennekes 
I just tested it with today's GitHub version and my original example still doesn't show titles in facets. @paulsromer 's example doesn't work either.

**Comment by mtennekes** [comment]
Strange, it works for me:

![Screenshot from 2021-02-27 10-06-14](https://user-images.githubusercontent.com/2444081/109382900-76bded80-78e3-11eb-9543-4503e1d79d31.png)
![Screenshot from 2021-02-27 10-05-42](https://user-images.githubusercontent.com/2444081/109382901-77ef1a80-78e3-11eb-9f2d-b7cc3335e877.png)

Any other testers?

**Comment by paulsromer** [comment]
The updated version works for me:
![image](https://user-images.githubusercontent.com/34322683/109390998-0f4b7200-78d2-11eb-855c-835fbf72b121.png)

**Comment by stragu** [comment]
My bad, you are right, it works now. Not sure where I went wrong when testing yesterday!
Thank you! :smiley:

**Comment by luukvdmeer** [comment]
(Annoying) question: is there also a way to *not* show the titles per facet? Mainly asking because when you run `tm_facets` with `as.layers = TRUE` the returned map gets the name of the first layer as overall map title, no mater which layers are turned on or off. Tried with setting `title = NA` but that does not seem to do it.

```r
library(osmdata)
library(tmap)

buildings <- opq(bbox = "west end, brisbane") %>% 
  add_osm_feature(key = "building") %>% 
  osmdata_sf() %>% 
  .$osm_polygons

tmap_mode("view")
tm_shape(buildings) +
  tm_polygons() +
  tm_facets(by = "wheelchair",  as.layers = TRUE)
```

![Screenshot from 2021-04-15 17-37-22](https://user-images.githubusercontent.com/26540305/114897399-7c2eb300-9e11-11eb-8386-7d94d9c5a0fd.png)

**Comment by Nowosad** [comment]
Hi @luukvdmeer - I am guessing, but have you tried to adjust the `panel.labels` argument of `tm_layout()`?

**Comment by abracadabbira** [comment]
Hi, 

When adding titles in view mode they are all showing up on one map when I knit the markdown file (knitting it as a flexdashboard file). Has anyone had this issue before? Please let me know. Thanks.

**Comment by stragu** [comment]
@abracadabbira I believe the issue you described is #441

**Comment by abracadabbira** [comment]
Yes, it is @stragu. However, what is the resolution? Thanks.
