### ISSUE TITLE
Mathematical annotation

### ISSUE THREAD

**Issue by sjewo** [mtennekes/tmap#55]
Hi Martijn,

another point on my wishlist:
I'd like to see support for mathematical annotations. At the moment it is not possible to use `expression()` in a legend title. 

I see, that this is not an easy task, because the use of expression will break code at many places. Maybe there are alternative solutions?

**Comment by mtennekes** [comment]
Hi Sebastian, could you give me an example how this by using `grid::grid.text()`?

**Comment by sjewo** [comment]
Hi Martijn,

here is a small example:
```
library(grid)

grid.newpage()
grid.text(expression(paste("population density by",m^{2}, " and ", alpha,"-value")))
```

The problem within tmap is, that the a expression object can't be coerced in a vector, while tmap often uses vectors to handle multiple values/labels.
```
label <- expression(paste("population density by",m^{2}, " and ", alpha,"-value"))
label.vec <- c(label, "another label")

is(label)
is(label.vec)
```

**Comment by mtennekes** [comment]
Thanks. Obviously, such expressions cannot be used with `tm_text`, since they cannot be a vector of a data.frame. Title, legend.title, credits, and category labels should be extended with expressions.
For text processing of all these elements, I find myself doing the same tricks again and again, such as determining the number of text lines. What I'll do, is to put these tasks into separate functions, which can then be extended to handle expressions.

**Comment by mtennekes** [comment]
Should be working as of https://github.com/mtennekes/tmap/commit/997a985d431f96363df0bcdade411316ec0c4a5a. See tests: https://github.com/mtennekes/tmap/blob/master/test/test_text_functions.R.

**Comment by sjewo** [comment]
Works great! Thanks a lot!

**Comment by johnbaums** [comment]
Could this be extended to `main.title` as well? 

```R
data(World)
tm_shape(World) + tm_borders() + tm_layout(main.title=expression(bold(abd)~def))
## Error in gmeta$main.title[k] != "" : 
##   comparison is not allowed for expressions
## In addition: Warning message:
## In is.na(main.title[1]) :
##   is.na() applied to non-(list or vector) of type 'expression'
```
