### ISSUE TITLE
offset

### ISSUE THREAD

**Issue by weijia2013** [mtennekes/tmap#568]
Is there a function or option that can offset lines (or links) of a sf object? For example, for roads, we could use one line to represent the road, but it has two directions and by offset, we can know they are different directions.

**Comment by mtennekes** [comment]
Yes, there is such a function called `double_line`, but it archived to the github repo `oldtmaptools` because it is based on the old `sp`. We could re-implement this function for `sf`, but I don't have time to do that myself.


``` r
library(oldtmaptools)
library(tmap)

data(rivers)

mississippi = rivers[which(rivers$name == "Mississippi"), ]

mississippi_dbl = double_line(mississippi, width = 0.1)
#> Warning: This function is deprecated and has been migrated to github.com/
#> mtennekes/oldtmaptools

#> Warning: This function is deprecated and has been migrated to github.com/
#> mtennekes/oldtmaptools

qtm(mississippi_dbl)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
```

![](https://i.imgur.com/imx85Ad.png)

<sup>Created on 2021-06-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
