### ISSUE TITLE
Multiple legend items next to each other (horizontal)

### ISSUE THREAD

**Issue by marionowak** [mtennekes/tmap#60]
Hello
I have a map like this:
![screenshot 2016-05-11 16 43 08](https://cloud.githubusercontent.com/assets/9657746/15184995/a7a55bc0-1797-11e6-93a6-bac3bcc8d969.png)

Pretty nice, but is it possible to have the legend items next to each on a horizontal line, so they don't take so much space?

Thanks for any hint!

**Comment by mtennekes** [comment]
Not possible yet, but it should be not very hard to implement. I think we can spread the legend items equally, and aligned them at the top, so that the legend titles are next to each other. So the only new argument to `tm_layout` would be `legend.stack` with `"vertical"` as default? `legend.width` and `

**Comment by mtennekes** [comment]
Done! It should be working. Minor thing is that `title.snap.to.legend = T` doesn't work yet for horizontally stacked legend items. Please test it if you have time.
