### ISSUE TITLE
multiple-variable tm_raster in viewing mode

### ISSUE THREAD

**Issue by yipcma** [mtennekes/tmap#63]
`library(tmap)`
`data(land)`
`tmap_mode("view")`
`tm_shape(land) + tm_raster("black") + tm_facets("cover_cls")`

This would only show one layer (land) and the whole thing is black. How should one use facets or multiple variables to create multiple layers in viewing mode?

Thanks.

**Comment by mtennekes** [comment]
Facets / small multiples are not supported in viewing mode. Currently, it ignores the faceting, so resulting in one black square.

I think it's a very good suggestion to translate small multiples to layers in viewing mode. It may not be straightforward to implement, since we need to take care of the 'normal' layers as well.

**Comment by mtennekes** [comment]
Already done
