### ISSUE TITLE
Migrate non-plotting functions to tmaptools?

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tmap#89]
Currently, tmap contains many non-plotting functions. The reason why I even bothered about writing these functions (e.g. `bb`, `append_data`, and `set_projection`) is that these functionalities were partly missing from the existing solutions, or I didn't found it as convenient as I would had liked. What I also didn't like as a user, is that the spatial non-plotting functions where all over the place.

However, from the user's perspective, it may be very confusing to have plotting and non-plotting functions combined in one package. Therefore, I think about migrating the plotting functions to a new package, `tmaptools`. `tmaptools` will still be imported in `tmap`, since many of the tool functions are used for plotting.

This adds to a broader discussion to create a single (umbrella) package for spatial data functions. See https://github.com/tim-salabim/rspatial/issues/5

I'm glad to hear your (@tim-salabim, @Robinlovelace @joelgombin @rsbivand @mdsumner @sjewo) opinions.

**Comment by Robinlovelace** [comment]
`bb()` is, as you say in the docs I think, a veritable Swiss Army knife for getting and adjusting the extent of bounding boxes: v. useful. Add to your list `sbind()`, which partly duplicates `raster::bind()` but which may (not confirmed) have some advantages over that. The priority for me is to enable as many people as possible to access such tools to make open source solutions to geospatial data challenges the go-to port of call. Offering them up to a community-led **geotools** package could help with that. I'm not sure simply removing them from **tmap** and putting them in *another* geospatial package will help improve the accessibility and knowledge of these functions though.

That's my first thoughts, look forward to hearing thoughts from others.

**Comment by tim-salabim** [comment]
I raised this issue in my review as part of the overarching messiness of the spatial universe in general (see link above). Splitting mapping and analysis tools into two different packages seems like the least we can try to do to not make things even more complicated within the larger framework. Therefore, I'd highly recommend moving the non-visual functions to an extra package as early as possible. It may not help in the short run to improve accessibility or lessen the user confusion, but it does no harm either and may in the long run be clearer to users (as it is obvious that tmaptools are needed for working with tmap). Plus, I am a fan of many small modules rather than one big module, but that is a personal preference I guess.

**Comment by Robinlovelace** [comment]
All good points Tim and yes I've no issue with it. Also if the package is imported or depended on by **tmap** it will ensure that it doesn't get lost.

**Comment by mtennekes** [comment]
I agree too. It will be much clearer for the user. Also, the documentation will automatically be more structured. This is my plan so far:

- move all non-viz functions from `tmap` to `tmaptools`
- of all non-exported functions, move those that are used solely by `tmaptools`-functions, and copy those that are used by both `tmap` and `tmaptools`, so they are accessible from both packages. Manual version control to keep them synced is needed. 
- let `tmap` import `tmaptools`
- let `tmaptools` suggest `tmap`, because `tmaptools` requires `tmap` to visualize the example results. I think this is possible without any circular dependency issue.

**Comment by tim-salabim** [comment]
are there many non-exported functions that both **tmap** and **tmaptools** use?

**Comment by sjewo** [comment]
In my opinion is a package split a good idea! I wasn't aware of the most non plotting functions and an separate package could make them more visible.
I'm unsure about the duplication of function code: If the non-exported functions are also useful outside the plotting functions they could be exported, otherwise you could put them into tmaptools and use the non-exported functions from within tmap and make tmaptools a dependency.

**Comment by mtennekes** [comment]
Thanks for your input! See https://github.com/mtennekes/tmaptools for the first commit.

There are not much non-exported functions. For convenience of maintainability they are placed in the `xxx_` files. Some of them could be worthwhile to export, however there are also some (ugly) processing functions, e.g. some functions in `xxx_raster` to deal with raster objects, which is not straight forward all the time. Not sure if all of these functions are actually used by the tmaptools functions.

@sjewo In the current `tmap` version, the `cartogram` function is imported from your package. In the light of this thread, and also for consistency with other shape-processing functions such as `smooth_map`, I'll put the `cartogram` package in the `suggests` of `tmap`, so that it can still be used in the its examples with `require(cartogram)`.
