### ISSUE TITLE
Tmap's view mode: use mapview?

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tmap#90]
The initial idea behind tmap's view mode was to have interactive mapping enabled, as easy as possible, both from user as maintainer perspective. From user perspective it is as easy as it gets, with just `tmap_mode("view")`. From maintenance point of view, it was very easy to use the R package leaflet.

Without additional effort, some plotting functionalities are not possible in view mode, most importantly, small multiples. As you may probably know, there is a great mapping package that also uses leaflet as base-package: `mapview`. It offers additional features, and also small multiples! The question rises whether we could/should base the viewing mode of tmap to mapview instead of leaflet directly?

Some pros and cons:

`+` mapview offers small multiples, and other useful additional features
`+` maintenance is easier, since mapview can take care of all recent development regarding interactive mapping
`+` `tmap` and `mapview` will not be competitors, but collaborators
`-` we would introduce another dependency; what if mapview stops updating after two years?
`-` mapview imports additional packages which would make tmap "heavier" to install:
```
Depends: R (>= 2.10), leaflet, methods
Imports: sp, raster, satellite, scales (>= 0.2.5), brew, htmlwidgets,
        htmltools, png, Rcpp (>= 0.11.3), lattice, latticeExtra, rgdal,
        gdalUtils, data.table, webshot, viridisLite
```

Another issues which is confusing from a user perspective: which method do you use to create an interactive leaflet-map? Currently, there are (at least) four, in order of low-level-functions/many-styling-possibilities to high-level-functions/less-styling-possibilities:

1. Skip R, and use JavaScript's leaflet library directly
2. R package leaflet
3. mapview
4. tmap

I'm glad to hear your (@tim-salabim, @Robinlovelace @joelgombin @edwindj @timelyportfolio @rsbivand @edzer @mdsumner @sjewo @jcheng5) opinions.

**Comment by Robinlovelace** [comment]
No comment other than to say `tmap_mode("view")` is fantastic and really useful that it works the same for static plotting.

**Comment by tim-salabim** [comment]
@mtennekes, I think this is quite a difficult choice from a tmap-package point of view as a mapview-based `tmap_mode("view")` would probably only make sense for method `qtm` (if we assume that `qtm` is for quick plotting and not final presentation-grade maps) where the user is not fussed about differences in looks between static and interactive map versions. The quasi-identical look between static and interactive maps, however, is quite desirable (as the comment by @Robinlovelace highlights). 

From the larger perspective discussed in https://github.com/tim-salabim/rspatial/issues/5 it is, of course, desirable to have as little overlap of functionality as possible between packages. If we agree that in the realm of interactive mapping mapview is for quick visual inspection and leaflet is for final presentation, then the logical choice for tmap would be to use mapview for `qtm` and leaflet for all other interactive mode maps.

**Comment by mtennekes** [comment]
Actually, there is no real difference between `qtm` and the main plotting method, other than the usage (exploratory vs. customized). Almost every map can be created with `qtm`, e.g. http://von-tijn.nl/tijn/research/presentations/tmap_user2015.pdf#11, and also facets. 

So I am particularly looking for a lightweight solution to mimic the static plots in view mode. Therefore, `tmap`'s view mode could use the following features, in order of importance:

1. Legend items for all aesthetics. Polygon color is there (squares), but bubbles, lines, and text legend cannot (easily) be made.
2. Small multiples.
3. Map attributes, such as scale bar, compass, and coordinate grid lines. 
4. Use non-Mercator map projections (with the downside that basemaps will not be available).

I'd like to hear you opinion whether 1) to use mapview for this, 2) extend the current view-mode implementation, or 3) to create a add-on package for leaflet, say, `leafletExtra`. The downside of 1 could be that `tmap` will get very bulky if `mapview` continues to expand with other features that are not related to `tmap` (see also my first post). My preferred option would be option 3.

**Comment by tim-salabim** [comment]
Regarding your list of desired features:

1. I agree that these missing legend options are needed. My best bet for this would be @bhaskarvk and his [leaflet.extras](https://github.com/bhaskarvk/leaflet.extras) package.
2. This can be done, as you know, with mapview.
3. For web-mercator projection these things are already available in the github version of leaflet afaik (though a compass is not necessary as north is always up). 
4. This point has been bugging me ever since I started mapview. We do have `plainView` but that currently only works for raster objects. This will obviously also need to be available for vector data and I think I have found a way how to implement this (it already works for data with `proj4string: NA`). Basically we scale the coordinates to lie between 0 and 1 and then draw at lon/lat 0/0. This way you loose the actual coordinates, yet you preserve the shape. I already have an idea how to get back the proper coordinates so they are shown correctly when the mouse is moved. However, this will likely only be for data viewing, i.e. without styling elements like a scalebar or grid lines.

I think all 3 scenarios are by themselves not optimal, but mixing those could be an option. You could, e.g. stick with your current view-mode implementation - after all it's best maintained by tmap to mimic static layout - but expand it by importing only `latticeView` from mapview (via `@importFrom`) which works with leaflet map objects so should be perfectly compatible with your view mode implementation. Also `mapview::addLargeFeatures` could be a good idea as this will enable viewing of large data sets such as your "crimes in greater London" example with leaflet. You could do the same with potentially implemented bubble etc legend options from leaflet.extras. I would not recommend creating yet another leaflet plugin package. Also, I am not quite sure how well you speak JavaSCRIPT which you really would need to be rather fluent in to develop extras on the JS side of things.

**Comment by mdsumner** [comment]
This is probably not helpful, but it's interesting that you have to work in 0,1 - and essentially TopoJSON works in a similar way, by rescaling so that all coordinates are integers. In your case the scaling would reflect the actual pixel canvas. Maybe there's an opportunity there ...
