### ISSUE TITLE
tm-symbols with multipart polygon

### ISSUE THREAD

**Issue by marionowak** [mtennekes/tmap#92]
I want to create a symbol map using ggplot charts that are placed on a map.
The polygons are administrative units which sometimes consist of multiple shapes with the same name and ID. How can I achieve that each grob is only displayed once per administrative unit and not on every polygon?

**Comment by joelgombin** [comment]
I think the easiest way to do that would be to preprocess the shape by using the `unionSpatialPolygons` function from the `maptools` package, which will consolidate the polygons so that there's only one polygon per unit. 
What I'm not sure about is how relevant the place where the grob is displayed will be...

**Comment by marionowak** [comment]
Ok, sounds good, but how can the attributes of the SpatialPolygonsDataFrame be kept?

**Comment by mtennekes** [comment]
Ah, just wrote a function for that a couple of weeks ago: `aggregate_map`. It is contained in `tmap`, but will soon be migrated to `tmaptools`.

**Comment by marionowak** [comment]
cool, thanks.
one other thing: how are the grobs matched to which polygon they belong?  until, something is messed up in my map. I tried to supply the same ID that was used to generate the plots, but it still looks wrong...

**Comment by mdsumner** [comment]
Maybe ?disaggregate (sp I think) is needed here, but also an example would be useful.
