### ISSUE TITLE
Rotated maps

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#95]
I wonder if there would be a way to plot rotated maps (i.e. where the North is arbitrarily oriented). I know for mapview/leaflet there are discussions regarding this issue, but here I'm only interested in the static/print version of the map. What do you think @mtennekes?

**Comment by joelgombin** [comment]
One lead could be to use the `orientation` argument in the `mapproj::mapproject` function?

**Comment by joelgombin** [comment]
FYI, I've tried using an oblique Mercator projection, but I encounter an error: 

```r
Error in (function (shp, unit = "metric", coords.unit = NA, unit.size = NA,  : 
  Unknown coords.unit: please specify unit.size.
```

**Comment by mdsumner** [comment]
There are a lot of projections that provide arbitrary "rotation", but it's a local property, not a global one like you seem to be after. Consider a polar map (Lambert Azimuthal Equal Area or Polar Stereographic, north is only "up" at one longitude, and even then it depends on where the central latitude is (possibly not an actual pole). 

 I'm happy to help see if you can get what you need with map projections (especially the Oblique Mercator :), can you describe the use-case more, and give a real example?  

Also fwiw you could probably use the Tissot Indicatrix to indicate where north actually is for localities in a single map:  https://github.com/mdsumner/tissot (mostly not written by me).

**Comment by joelgombin** [comment]
@mdsumner I do understand that arbitrary rotation can only be a local property. I think a good place to start with would be to allow the user to rotate commonly used projections, let's say the web mercator to start with, and possibly Lamberts. 

Here is an example where using an Oblique Mercator seems possible, but tmap fails to map it:


```r
library(tmap)
data(Europe)

tm_shape(Europe) +
  tm_polygons()

Europe2 <- spTransform(Europe, CRS("+proj=omerc +lat_0=42 +gamma=0 +lonc=10 +alpha=-90 +k_0=1 +x_0=0 +y_0=0"))

plot(Europe2) # works

tm_shape(Europe2) +
  tm_polygons() 
# fails with  Error in (function (shp, unit = "metric", coords.unit = NA, unit.size = NA,  : 
#  Unknown coords.unit: please specify unit.size.
```

**Comment by mtennekes** [comment]
Great suggestion. In the same direction, I wonder whether it is possible to show world maps with non-standard centers, e.g. an Australia-centered map. Probably it will after some minor improvements.

`tmap` fails because the "+units="  attribute is missing in the projection string. However, it should not result in an error. The units are only needed for scale bars and the calculation of density value. In these cases it should throw a warning instead.

I'll fix this. A workaround is:

```{r}
tm_shape(Europe2, unit="m", unit.size=1) +
  tm_polygons() 
```

**Comment by mdsumner** [comment]
Can the viewport be rotated? (at least for the global page-orientation mode).

I think the projection approach will be hard to generalize, but happy to die trying :)  Thanks for the examples and workaround

**Comment by mtennekes** [comment]
Yes, that is possible! See the `angle` argument in `grid::viewport`. Not sure this is the ideal solution, as text labels will also be rotated. I think it is better to rotate the coordinates of each grob object (which is the result from translating the shape coordinates to the 0-1 range), around (.5, .5).

**Comment by mdsumner** [comment]
Just a heads-up prompted by this: @edzer has some nice affine examples for modifying sf objects in the 3rd vignette http://edzer.github.io/sfr/articles/sf3.html  and dev ggplot2 now has support for the grobs in sf.

**Comment by ratnanil** [comment]
Are there any updates to this question, considering V4?

**Comment by mtennekes** [comment]
@ratnanil seeing this now.

This example from @mdsumner works:

```r
Europe = World[World$continent == "Europe", ]
tm_shape(Europe) +
	tm_polygons() +
	tm_crs("+proj=omerc +lat_0=42 +gamma=0 +lonc=10 +alpha=-90 +k_0=1 +x_0=0 +y_0=0")
```

![Image](https://github.com/user-attachments/assets/495b9b6c-3a5c-4a86-8fe1-d5c09c69c522)

**Comment by mtennekes** [comment]
The issue of pixelization only happens when you rotate an image, right?

It's indeed possible to rotate an image via the grid package but only via the viewport. So we could add a rotated viewport and make it large enough that it contains the target (straight) map frame, and apply clipping. But this would probably be the most advanced use case of the grid package I've seen so far.

The basemaps via `maptiles` work fine for rotated maps, even though they are a bit blurry.

```r
Italy = World[World$iso_a3 == "ITA", ]
tm_shape(Italy) +
    tm_borders(lwd = 3, col = "red") +
    tm_crs("+proj=omerc +lat_0=42 +gamma=0 +lonc=10 +alpha=-90 +k_0=1 +x_0=0 +y_0=0") +
    tm_basemap("CartoDB.Voyager")
#> [basemaps] Tiles from "CartoDB.Voyager" will be projected so details (e.g.
#> text) could appear blurry
#> This message is displayed once per session.
```

![](https://i.imgur.com/L5V58ij.png)

 Thunderforest and Stadia maps offer 'retina' versions which could result in a bit sharper images.
